### ISSUE TITLE
Private registry as a pull through cache and replace registry with nexus3

### ISSUE THREAD

**Issue by ahinko** [ahinko/k8s-cluster#6]
To eliminate any problems with the [Docker hub rate limits](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/) we should use our private registry as a cache.

## Todo:
- [x] Replace registry with [nexus3](https://help.sonatype.com/repomanager3)
- [x] We probably also need to update `/etc/rancher/k3s/registries.yaml` to something like this:
```
mirrors:
  "registry.komhem.xyz":
    endpoint:
      - "http://registry.komhem.xyz"
  "docker.io":
    endpoint:
      - "http://registry.komhem.xyz"
      - "https://docker.io"
configs:
  "docker.io":
    auth:
      username: <username>
      password: <password>
  "registry.komhem.xyz":
    auth:
      username: <username>
      password: <password>

```

## Links
https://medium.com/faun/deploy-sonatype-nexus-repository-oss-v3-with-docker-a50225fe661e
